apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortexcloud-app
  labels:
    app: cortexcloud
spec:
  replicas: 3  # adjust replicas for desired scalability
  selector:
    matchLabels:
      app: cortexcloud
  template:
    metadata:
      labels:
        app: cortexcloud
    spec:
      containers:
        - name: cortexcloud-container
          image: public.ecr.aws/v4r8s5f3/hankthebldr/cortexcloud:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cortexcloud-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
    - port: 5005
      targetPort: 5005
      protocol: TCP
  selector:
    app: cortexcloud